name: Build & Deploy Sanity Studio
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build & Deploy Sanity Studio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Project Dependencies
        run: yarn
        working-directory: studio
      - name: Install Sanity CLI
        run: yarn global add  @sanity/cli
      - name: Build Studio
        run: sanity build
        working-directory: studio
